In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [3]:
df = pd.read_csv('Train_Data.csv')
df

SEQN  RIAGENDR  PAQ605  BMXBMI  LBXGLU  DIQ010  LBXGLT  LBXIN  \
0     73564.0       2.0     2.0    35.7   110.0     2.0   150.0  14.91   
1     73568.0       2.0     2.0    20.3    89.0     2.0    80.0   3.85   
2     73576.0       1.0     2.0    23.2    89.0     2.0    68.0   6.14   
3     73577.0       1.0     2.0    28.9   104.0     NaN    84.0  16.15   
4     73580.0       2.0     1.0    35.9   103.0     2.0    81.0  10.92   
...       ...       ...     ...     ...     ...     ...     ...    ...   
1961  83711.0       2.0     2.0    33.5   100.0     2.0    73.0   6.53   
1962  83712.0       1.0     2.0    30.0    93.0     2.0   208.0  13.02   
1963  83713.0       1.0     2.0    23.7   103.0     2.0   124.0  21.41   
1964  83718.0       2.0     2.0    27.4    90.0     2.0   108.0   4.99   
1965  83727.0       1.0     2.0    24.5     NaN     2.0   108.0   3.76   

     age_group  
0        Adult  
1        Adult  
2        Adult  
3        Adult  
4        Adult  
...        ...  
1961     Adult  
1962     Adult  
1963     Adult  
1964     Adult  
1965     Adult  

[1966 rows x 9 columns]

In [4]:
df.drop('SEQN',axis=1,inplace=True)
df.head(10)

RIAGENDR  PAQ605  BMXBMI  LBXGLU  DIQ010  LBXGLT  LBXIN age_group
0       2.0     2.0    35.7   110.0     2.0   150.0  14.91     Adult
1       2.0     2.0    20.3    89.0     2.0    80.0   3.85     Adult
2       1.0     2.0    23.2    89.0     2.0    68.0   6.14     Adult
3       1.0     2.0    28.9   104.0     NaN    84.0  16.15     Adult
4       2.0     1.0    35.9   103.0     2.0    81.0  10.92     Adult
5       1.0     2.0    23.6   110.0     2.0   100.0   6.08     Adult
6       1.0     2.0    38.7    94.0     2.0   202.0  21.11     Adult
7       2.0     2.0    38.3   107.0     2.0   164.0  20.93     Adult
8       1.0     2.0    38.9    89.0     2.0   113.0  17.47    Senior
9       1.0     1.0    28.9    90.0     2.0    95.0   3.24     Adult

In [5]:
df['age_group']=df['age_group'].apply(lambda x:1 if x=='Senior' else 0)
df.head(10)

RIAGENDR  PAQ605  BMXBMI  LBXGLU  DIQ010  LBXGLT  LBXIN  age_group
0       2.0     2.0    35.7   110.0     2.0   150.0  14.91          0
1       2.0     2.0    20.3    89.0     2.0    80.0   3.85          0
2       1.0     2.0    23.2    89.0     2.0    68.0   6.14          0
3       1.0     2.0    28.9   104.0     NaN    84.0  16.15          0
4       2.0     1.0    35.9   103.0     2.0    81.0  10.92          0
5       1.0     2.0    23.6   110.0     2.0   100.0   6.08          0
6       1.0     2.0    38.7    94.0     2.0   202.0  21.11          0
7       2.0     2.0    38.3   107.0     2.0   164.0  20.93          0
8       1.0     2.0    38.9    89.0     2.0   113.0  17.47          1
9       1.0     1.0    28.9    90.0     2.0    95.0   3.24          0

In [6]:
df.isna().sum()

RIAGENDR     18
PAQ605       13
BMXBMI       18
LBXGLU       13
DIQ010       18
LBXGLT       11
LBXIN         9
age_group     0
dtype: int64

In [7]:
df['PAQ605'].unique()

array([ 2.,  1., nan,  7.])

In [8]:
df['RIAGENDR'].unique()

array([ 2.,  1., nan])

In [9]:
df['DIQ010'].unique()

array([ 2., nan,  1.,  3.])

In [10]:
sum(df['PAQ605']==7)

1

In [11]:
df.loc[df['PAQ605']==7]

RIAGENDR  PAQ605  BMXBMI  LBXGLU  DIQ010  LBXGLT  LBXIN  age_group
359       1.0     7.0    21.1   110.0     2.0    66.0   4.24          0

In [12]:
df.drop(359,axis=0)

RIAGENDR  PAQ605  BMXBMI  LBXGLU  DIQ010  LBXGLT  LBXIN  age_group
0          2.0     2.0    35.7   110.0     2.0   150.0  14.91          0
1          2.0     2.0    20.3    89.0     2.0    80.0   3.85          0
2          1.0     2.0    23.2    89.0     2.0    68.0   6.14          0
3          1.0     2.0    28.9   104.0     NaN    84.0  16.15          0
4          2.0     1.0    35.9   103.0     2.0    81.0  10.92          0
...        ...     ...     ...     ...     ...     ...    ...        ...
1961       2.0     2.0    33.5   100.0     2.0    73.0   6.53          0
1962       1.0     2.0    30.0    93.0     2.0   208.0  13.02          0
1963       1.0     2.0    23.7   103.0     2.0   124.0  21.41          0
1964       2.0     2.0    27.4    90.0     2.0   108.0   4.99          0
1965       1.0     2.0    24.5     NaN     2.0   108.0   3.76          0

[1965 rows x 8 columns]

In [13]:

sns.pairplot(df)

In [14]:
sns.jointplot(x='BMXBMI', y='LBXIN', data=df,hue='RIAGENDR')

In [15]:
df.dropna(subset=['RIAGENDR','PAQ605','DIQ010'],how='any',inplace=True)

In [16]:
df.isna().sum()

RIAGENDR      0
PAQ605        0
BMXBMI       18
LBXGLU       13
DIQ010        0
LBXGLT       11
LBXIN         9
age_group     0
dtype: int64

In [17]:
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer


In [18]:
feature_cols=['RIAGENDR','PAQ605','BMXBMI','LBXGLU','DIQ010','LBXGLT','LBXIN']

In [19]:
df_iterative_imputer = df.copy()
itr_imputer = IterativeImputer()
df_iterative_imputer[feature_cols] = itr_imputer.fit_transform(df_iterative_imputer[feature_cols])

In [20]:
df_iterative_imputer.head(20)

RIAGENDR  PAQ605  BMXBMI  LBXGLU  DIQ010  LBXGLT  LBXIN  age_group
0        2.0     2.0    35.7   110.0     2.0   150.0  14.91          0
1        2.0     2.0    20.3    89.0     2.0    80.0   3.85          0
2        1.0     2.0    23.2    89.0     2.0    68.0   6.14          0
4        2.0     1.0    35.9   103.0     2.0    81.0  10.92          0
5        1.0     2.0    23.6   110.0     2.0   100.0   6.08          0
6        1.0     2.0    38.7    94.0     2.0   202.0  21.11          0
7        2.0     2.0    38.3   107.0     2.0   164.0  20.93          0
8        1.0     2.0    38.9    89.0     2.0   113.0  17.47          1
9        1.0     1.0    28.9    90.0     2.0    95.0   3.24          0
10       2.0     2.0    32.7    98.0     2.0    80.0   7.16          0
11       2.0     1.0    27.3    85.0     2.0    91.0   9.86          0
12       1.0     2.0    24.6   100.0     2.0    97.0   4.33          1
13       2.0     2.0    30.5   102.0     2.0   124.0  12.06          0
14       1.0     2.0    30.3   133.0     2.0   295.0  22.92          1
15       2.0     1.0    22.1   114.0     2.0   150.0  10.09          1
16       2.0     2.0    37.8    96.0     2.0   120.0   9.61          0
17       1.0     2.0    28.0    89.0     2.0    82.0   8.39          0
18       1.0     2.0    21.0    86.0     2.0    84.0   4.47          0
19       1.0     2.0    33.0   108.0     2.0    77.0   8.02          0
20       1.0     2.0    29.1    99.0     2.0    95.0   6.12          0

In [21]:
df_iterative_imputer.isna().sum()

RIAGENDR     0
PAQ605       0
BMXBMI       0
LBXGLU       0
DIQ010       0
LBXGLT       0
LBXIN        0
age_group    0
dtype: int64

In [22]:
from sklearn.model_selection import train_test_split
X=df_iterative_imputer.drop('age_group',axis=1)
y=df_iterative_imputer.age_group

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [23]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
def print_score(clf,X_train,y_train,X_test,y_test,train=True):
    if train:
        pred = clf.predict(X_train)
        clf_report = pd.DataFrame(classification_report(y_train,pred,output_dict= True))
        print("Train Result:\n================================================")
        print(f"Accuracy Score: {accuracy_score(y_train, pred) * 100:.2f}%")
        print("_______________________________________________")
        print(f"CLASSIFICATION REPORT:\n{clf_report}")
        print("_______________________________________________")
        print(f"Confusion Matrix: \n {confusion_matrix(y_train, pred)}\n")

    elif train==False:
        pred = clf.predict(X_test)
        clf_report = pd.DataFrame(classification_report(y_test, pred, output_dict=True))
        print("Test Result:\n================================================")        
        print(f"Accuracy Score: {accuracy_score(y_test, pred) * 100:.2f}%")
        print("_______________________________________________")
        print(f"CLASSIFICATION REPORT:\n{clf_report}")
        print("_______________________________________________")
        print(f"Confusion Matrix: \n {confusion_matrix(y_test, pred)}\n")

In [24]:
from sklearn.ensemble import RandomForestClassifier
rf_clf = RandomForestClassifier(n_estimators=100)
rf_clf.fit(X_train,y_train)
print_score(rf_clf,X_train,y_train,X_test,y_test,train=True)
print_score(rf_clf,X_train,y_train,X_test,y_test,train=False)

Train Result:
Accuracy Score: 100.00%
_______________________________________________
CLASSIFICATION REPORT:
                0      1  accuracy  macro avg  weighted avg
precision     1.0    1.0       1.0        1.0           1.0
recall        1.0    1.0       1.0        1.0           1.0
f1-score      1.0    1.0       1.0        1.0           1.0
support    1290.0  243.0       1.0     1533.0        1533.0
_______________________________________________
Confusion Matrix: 
 [[1290    0]
 [   0  243]]

Test Result:
Accuracy Score: 83.07%
_______________________________________________
CLASSIFICATION REPORT:
                    0          1  accuracy   macro avg  weighted avg
precision    0.844687   0.529412  0.830729    0.687049      0.790499
recall       0.974843   0.136364  0.830729    0.555603      0.830729
f1-score     0.905109   0.216867  0.830729    0.560988      0.786818
support    318.000000  66.000000  0.830729  384.000000    384.000000
___________________________________________

In [25]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV

n_estimators= [100,200,300,400]
max_features=['auto','sqrt']
max_depth = [2,3,5]
max_depth.append(None)
min_samples_split = [2,5,10]
min_samples_leaf = [1,2,4,10]
bootstrap = [True,False]

params_grid = {
    'n_estimators':n_estimators,
    'max_features':max_features,
    'max_depth':max_depth,
    'min_samples_split':min_samples_split,
    'min_samples_leaf':min_samples_leaf,
    'bootstrap':bootstrap
}
rf_clf= RandomForestClassifier(random_state=42)
rf_cv = GridSearchCV(
    rf_clf,
    params_grid,
    scoring='f1',
    cv=5,
    verbose=1,
    n_jobs=-1



)
rf_cv.fit(X_train,y_train)
best_params = rf_cv.best_params_
print(f"Best parameters: {best_params}")

rf_clf= RandomForestClassifier(**best_params)
rf_clf.fit(X_train,y_train)
print_score(rf_clf, X_train, y_train, X_test, y_test, train=True)
print_score(rf_clf, X_train, y_train, X_test, y_test, train=False)



Fitting 5 folds for each of 768 candidates, totalling 3840 fits


c:\ProgramData\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:540: FitFailedWarning: 
1920 fits failed out of a total of 3840.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
902 fits failed with the following error:
Traceback (most recent call last):
  File "c:\ProgramData\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 888, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "c:\ProgramData\anaconda3\Lib\site-packages\sklearn\base.py", line 1466, in wrapper
    estimator._validate_params()
  File "c:\ProgramData\anaconda3\Lib\site-packages\sklearn\base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "c:\ProgramData\anaconda3\Lib\site-pack

Best parameters: {'bootstrap': False, 'max_depth': None, 'max_features': 'sqrt', 'min_samples_leaf': 2, 'min_samples_split': 5, 'n_estimators': 200}
Train Result:
Accuracy Score: 99.02%
_______________________________________________
CLASSIFICATION REPORT:
                     0           1  accuracy    macro avg  weighted avg
precision     0.988506    1.000000  0.990215     0.994253      0.990328
recall        1.000000    0.938272  0.990215     0.969136      0.990215
f1-score      0.994220    0.968153  0.990215     0.981186      0.990088
support    1290.000000  243.000000  0.990215  1533.000000   1533.000000
_______________________________________________
Confusion Matrix: 
 [[1290    0]
 [  15  228]]

Test Result:
Accuracy Score: 82.29%
_______________________________________________
CLASSIFICATION REPORT:
                    0          1  accuracy   macro avg  weighted avg
precision    0.843407   0.450000  0.822917    0.646703      0.775790
recall       0.965409   0.136364  0.822917

In [26]:
test_df=pd.read_csv('Test_Data.csv')
test_df.drop('SEQN',axis=1,inplace=True)

In [27]:
y_pred = rf_clf.predict(test_df)
y_pred

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [28]:
output_df = pd.DataFrame({'age_group': y_pred})
output_df.to_csv('submission2.csv', index=False)